ExpediaGroup/feast

setup.py

Renames the package to "feast"
None created
Fixes #
Package naming

Rename to feast

---

.gitignore
protos/feast/core/FeatureView.proto
sdk/python/feast/errors.py
sdk/python/feast/expediagroup/pydantic_models/data_source_model.py
sdk/python/feast/expediagroup/pydantic_models/entity_model.py
sdk/python/feast/expediagroup/pydantic_models/feature_service.py
sdk/python/feast/expediagroup/pydantic_models/feature_view_model.py
sdk/python/feast/expediagroup/pydantic_models/field.py
sdk/python/feast/expediagroup/pydantic_models/field_model.py
sdk/python/feast/expediagroup/pydantic_models/project_metadata_model.py
sdk/python/feast/feature_view.py
sdk/python/feast/feature_view_projection.py
sdk/python/feast/field.py
sdk/python/feast/infra/registry/sql.py
sdk/python/feast/types.py
sdk/python/tests/unit/test_pydantic_models.py
sdk/python/tests/unit/test_types.py

Fixes #
1. Added pydantic support for Field, FeatureViewProjections, OnDemandFeatureViews, Feature Services and Project Metadata
2. original_entities is added to Feast protos so we can preserve the user input
3. Fixed issues observed during the Registry service testing for Entity, Datasource, Feature Views
4. Added ProjectMetadataNotFoundException exception when the requested project doesn't exists
5. SQL Registry has methods to get project uuid and project last updated timestamp separately. Created new functions which will return ProjectMetadataModel objects. Helps in registry service

feat: Added pydantic model support for ODFV and Feature Services

---

.github/workflows/unit_tests.yml
sdk/python/feast/expediagroup/pydantic_models/field_model.py
sdk/python/feast/expediagroup/pydantic_models/project_metadata_model.py
sdk/python/feast/feature_store.py
sdk/python/feast/infra/registry/http.py
sdk/python/feast/infra/registry/registry.py
sdk/python/feast/infra/registry/sql.py
sdk/python/feast/repo_config.py
sdk/python/requirements/py3.10-ci-requirements.txt
sdk/python/requirements/py3.8-ci-requirements.txt
sdk/python/requirements/py3.9-ci-requirements.txt

Fixes #
1. Fixed date conversion issues and import issue during the validation of HTTP Registry
2. Fixed the issue while running unit-test workflow “ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze' (/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/pip/_internal/commands/freeze.py)” by upgrading pip-tools version to 7.1.0 (latest)
NOTE: Tests will be added later

feat: Added support for HTTP Registry

---

sdk/python/feast/infra/registry/http.py

Fixes #
Disabled SSL verification

fix: disable ssl verification for http registry

---

protos/feast/core/VectorFeatureView.proto
sdk/python/feast/expediagroup/vectordb/index_type.py
sdk/python/feast/expediagroup/vectordb/vector_feature_view.py
sdk/python/tests/expediagroup/test_vector_feature_view.py

it adds a VectorFeatureView as part of the integration of vector dbs

feat: adding a feature view for vector database integration

---

sdk/python/feast/infra/registry/sql.py

Fixes #
Solves the automatic closing of connections when idle for longer duration

fix: added pool_recycle option to create_engine

---

sdk/python/feast/expediagroup/vectordb/milvus_online_store.py
sdk/python/tests/expediagroup/test_milvus_online_store.py

Added Write batch functionality for Milvus
Fixes #

Added milvus write batch functionality

---

sdk/python/tests/expediagroup/test_milvus_online_store.py

Fixes #
fixes the broken Milvus unit-test

fixed unit-test that was broken after last merge to master

---

Makefile
docs/reference/online-stores/milvus.md
setup.py

this adds documentation for the Milvus online store
Fixes #

first draft of Milvus online store documentation

---

sdk/python/feast/expediagroup/vectordb/milvus_online_store.py
sdk/python/tests/expediagroup/test_milvus_online_store.py

this adds the implementation of the teardown method to the Milvus online store
Fixes #

added teardown method to Milvus online store

---

sdk/python/feast/expediagroup/vectordb/milvus_online_store.py

Fixes #
this will fix issues with the timestamp field and also do a mapping for strings. It is meant to be a hotfix for UAT

hot-fixed type mappings - will need rework

---

sdk/python/feast/feature_store.py
sdk/python/feast/infra/passthrough_provider.py

print statements added to help debug milvus
Fixes #

add debug prints for tracking apply flow

---

sdk/python/feast/feature_store.py
sdk/python/feast/infra/passthrough_provider.py

fixc linting

---

sdk/python/feast/expediagroup/vectordb/milvus_online_store.py
sdk/python/feast/feature_store.py
sdk/python/feast/infra/passthrough_provider.py
sdk/python/tests/expediagroup/test_milvus_online_store.py

Fixes #
this will be a temporary workaround due to the update method not being called when a feature view is registered. A collection will be created on write if it not already exists

temporary workaround to create a collection on write if it not exists

---

sdk/python/feast/expediagroup/vectordb/milvus_online_store.py

strip removes any of the characters given, we need to remove a substring with replace instead.
Fixes #

use replace instead of strip

---

go/internal/feast/transformation/transformation.go

fix linting

---

sdk/python/feast/infra/registry/http.py
sdk/python/feast/infra/registry/sql.py
sdk/python/tests/unit/test_sql_registry.py

- Refreshes SQL registry cache as a separate thread
- Uses ThreadPoolExecutor to refresh projects cache concurrently

fix: Refresh sql registry in background

---

docs/reference/online-stores/milvus.md

Fixes #
brings more clarity on how to configure a feature view that's used by Milvus online store

feat: updated the Milvus online store documentation

---

go/internal/feast/registry/http.go

Using feature view list instead of feature view during unmarshal process

using feature view list instead of feature view

---

go/internal/feast/transformation/transformation.go

Improves panic handling for better error catching
Fixes #

improve panic handling for python transformation

---

sdk/python/feast/infra/registry/http.py
sdk/python/feast/infra/registry/sql.py

fix: SQL Engine Increase poolsize to 10

fix: increase sql engine conneciton pool size to 10

---

sdk/python/feast/embedded_go/online_features_service.py

- add exception handling in python side of odfv

error catching around pyarrow to pandas convertion

---

go.mod
go.sum
go/internal/feast/transformation/transformation.go

Revert "create an isolated child process to run unsafe code and CFFI"

---

go.mod
go.sum
go/internal/feast/transformation/transformation.go

include cgosymbolizer for CPython debugging

---

sdk/python/feast/expediagroup/vectordb/elasticsearch_online_store.py
sdk/python/tests/expediagroup/test_elasticsearch_online_store.py

Implement online_batch_write method for elasticsearch online store

implement write batch method for elasticsearch online store

---

sdk/python/feast/expediagroup/pydantic_models/feature_view_model.py
sdk/python/tests/unit/test_pydantic_models.py

Add timestamp fields to Feature View Pydantic models to allow creation of timestamps
Fixes # https://jira.expedia.biz/browse/EAPC-11402

fix: Add changes to Feature View Pydantic model to support timestamps

---

sdk/python/feast/infra/registry/http.py

fix: Using exception chaining ratherthan new exception

---

protos/feast/core/DataFormat.proto
sdk/python/feast/data_format.py
sdk/python/feast/expediagroup/pydantic_models/data_source_model.py
sdk/python/feast/expediagroup/pydantic_models/stream_format_model.py
sdk/python/feast/infra/contrib/spark_kafka_processor.py
sdk/python/tests/unit/test_pydantic_models.py

Fixes #
Spark Streaming Ingestion support reading from Confluent Kafka

feat: Added support for Confluent Avro Format

---

go/internal/feast/featurestore.go
go/internal/feast/server/http_server.go
go/internal/feast/transformation/transformation.go

Fixes #
- Error response in Json format `{
"error": "Error getting feature vector: feature View mlpfs_bdodla_playground_view1 doesn't exist, please make sure that you have created the feature View mlpfs_bdodla_playground_view1 and that you have registered it by running \"apply\"",
"status_code": 500
}`
- tracing time for online store and transformation calls as future references
- Added trace_id and span_id to logs. Logs look like `{"level":"error","trace_id":2360390540312468693,"span_id":8107743037168700757,"error":"feature View mlpfs_bdodla_playground_view1 doesn't exist, please make sure that you have created the feature View mlpfs_bdodla_playground_view1 and that you have registered it by running …

fix: Formatting go error responses to JSON

---

.gitignore
sdk/python/feast/data_source.py
sdk/python/feast/expediagroup/provider/expedia.py
sdk/python/feast/feature_store.py
sdk/python/feast/infra/contrib/spark_kafka_processor.py
sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
sdk/python/feast/infra/provider.py
sdk/python/feast/infra/registry/http.py
sdk/python/feast/repo_config.py
sdk/python/tests/unit/infra/scaffolding/test_repo_config.py

Fixes #
1. Added expedia provider which defaults batch engine to spark and offline store to spark
2. Deletion of extra columns from dataframe is moved to provider so we can support updates in feature view in stream
3. Spark process by partition is now supports batching so we can process by batches. Batching can be defined at feature_store.yaml level or feature view level as a tag. Merged the conversion to dataframe rows to list and then to pandas data frame stages to direct pandas dataframe so we can save memory for the list

feat: Added expedia provider and batching materialization process

---

sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
sdk/python/requirements/py3.10-ci-requirements.txt
sdk/python/requirements/py3.8-ci-requirements.txt
sdk/python/requirements/py3.9-ci-requirements.txt
setup.py

Fixes #
- Fixes error writing to Redis during the Cluster Scaling activity. Error is `AttributeError: 'ClusterPipeline' object has no attribute '_lock'`
- Logging message updates

fix: Redis version upgrade

---

go.mod
go.sum
go/internal/feast/onlinestore/redisonlinestore.go
go/internal/feast/onlinestore/redisonlinestore_test.go
go/internal/feast/server/http_server.go

Fixes #
- chore: Updated redis version and refactored redis online read
- Enabled Datadog redis tracing using ENABLE_DATADOG_REDIS_TRACING environment variable when necessary

chore: Updated redis version and refactored redis online read

---

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py

fix: bytewax engine create configmap from object
Fixes #

fix: Bytewax engine create configmap from object (#3821)

---

go/internal/feast/onlinestore/redisonlinestore.go
go/internal/feast/registry/http.go
sdk/python/feast/infra/online_stores/redis.py

Additional logging to help in displaying Redis cluster endpoints used

chore: Added logging to print cluster endpoint used

---

sdk/python/feast/errors.py
sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py

1. Imports grpc only for type checking. Avoids installation of grpcio dependencies
2. Commenting the warning to avoid confusion for users

fix: Import grpc only for type checking

---

sdk/python/feast/infra/contrib/spark_kafka_processor.py
sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py

1. Creates the infra as part of spark kafka processor streaming ingestion

feat: Create infra as part of the streaming ingestion

---

setup.py

Added constraints based on open source feast setup.py

fix: Update ScyllaDB required dependencies

---

sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
sdk/python/tests/unit/infra/online_store/test_cassandra_online_store.py

Check if object is SortedFeatureView type and then create table using CQL .
New CQL statement for this specific feature.
Relevant unit tests

feat: Adding create table functionality for sorted feature view

---

sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py

Adding an improvement to the Cassandra create table code.

feat: Adding Improvement to the Scylla Create Table Functionality for Range Query

---

sdk/python/feast/errors.py
sdk/python/feast/feature_store.py
sdk/python/feast/infra/registry/http.py
sdk/python/feast/infra/registry/sql.py

Adding SortedFeatureView Custom Exception Type and improvements

feat: Adding SortedFeatureView Custom Exception Type and Improvements

---

java/CONTRIBUTING.md
java/serving-client/src/main/java/dev/feast/FeastClient.java
java/serving-client/src/test/java/dev/feast/FeastClientTest.java

Changelog: 
1/ Add support in the serving-client for featureService as an input to getOnlineFeatures. Most of the changes are refactoring/adding a test.

feat: Add feature service support to serving-client/FeastClient in java SDK

---

sdk/python/feast/infra/registry/caching_registry.py
sdk/python/feast/infra/registry/sql.py

fix: Revert caching registry changes

---

sdk/python/feast/infra/registry/sql.py

feat: Log execution times of self.proto() in sql registry

---

sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py

Exclude regular feature views from changes in https://jira.expedia.biz/browse/EAPC-16964 
https://jira.expedia.biz/browse/EAPC-17872

fix: Exclude regular feature views from TTL implementation

---

go/internal/feast/onlineserving/serving.go
go/internal/feast/onlineserving/serving_test.go
go/internal/feast/onlinestore/egvalkeyonlinestore.go

1. Refactored `ValidateFeatureRefs` and `ValidateSortedFeatureRefs` methods which identify if any features requested leads to a collision or not. Added tests and benchmark tests to the above methods.
2. Refactored `OnlineRead` method for Valkey. Removed duplicate code to calculate `timestamp` field and also using map so it gets calculated once and reused for further features specific to feature view. Removed duplicate code for assigning `FeatureData` object as well.

refactor: Valkey onlineRead and validateFeatureRef methods

---

go/internal/feast/server/grpc_server.go
go/internal/feast/server/hybrid_server.go
go/main.go
sdk/python/feast/sort_key.py
sdk/python/feast/sorted_feature_view.py
sdk/python/tests/unit/test_sorted_feature_view.py

Adding additional validation to sort key object in Sorted Feature View support for range querying.

feat: Add Additional Sort Key Validation

---

sdk/python/feast/infra/registry/sql.py

Fixing exception return type for SFV

fix: Exception Type for SFV

---

go/internal/feast/onlineserving/serving.go
go/internal/feast/onlinestore/cassandraonlinestore.go
go/internal/feast/server/http_server.go
go/internal/feast/server/http_server_test.go

This PR does:
1. Allow strings to be passed for byte type sort keys. This is necessary because http server does not provide type hints to differentiate byte from string.
2. Make online store return null values when feature value not found. 
3. Make the http server return list of list (previously it was returning list of list of list).

fix: Functional improvements to feature server

---

.github/workflows/go_integration_test.yml

fix: Create workflow for go integration tests

---

.github/workflows/go_integration_test.yml

fix: Update go int test trigger

---

java/serving-client/src/main/java/dev/feast/FeastClient.java

fix: Javadoc errors

---

sdk/python/feast/infra/contrib/spark_kafka_processor.py

Index resetting is only meant to be used after a groupby and not needed otherwise

fix: Fix misplaced reset indexes

---

java/serving-client/src/main/java/dev/feast/FeastClient.java

fix: Formatting javadocs

---

java/serving-client/src/main/java/dev/feast/FeastClient.java

fix: Formatting

---

go/internal/feast/onlineserving/serving.go
go/internal/feast/onlineserving/serving_test.go

fix: Validate requested features exist in view.
