- infra/scripts/setup-common-functions.sh
This script is responsible for giving the highest semver. It won't match on our `eg-v` tags, so we have to modify it. I think this is making docker publish fail in our build and publish action.
> Fix semver regex

- infra/scripts/setup-common-functions.sh
Reverts ExpediaGroup/feast#3
Versioning as `eg-vx.x.x` is not working. The eg-v gets cut off and the versioned docker images/wheels get uploaded as `feastx.x.x`. We need some way of marking which are EG builds and which aren't.
> Revert "Fix semver regex"

- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
This pr adds support for the file format, Apache Iceberg, to SparkSource.
Fixes #
1. Apache Iceberg format is supported when using Spark Offline Store. Materialization test using Iceberg format has been conducted.
> feat: Add Iceberg support to SparkSource

- sdk/python/feast/__init__.py
- sdk/python/feast/feature_view.py
- sdk/python/feast/infra/aws.py
- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
- sdk/python/tests/unit/test_sql_registry.py
Fixes #
1. Disabled data deletion from online store when feature view is deleted for AWS provider
2. Ignored warnings related to Spark and Feature view
> fix: disabled data deletion when feature view is deleted

- sdk/python/feast/expediagroup/vectordb/milvus_online_store.py
…ng materialisation process in feast since the logs statements aren't showing up
We are temporarily adding in print statements to understand where the materialization step is failing for Milvus online store since the logging isn't showing up
Fixes #
> Adding print statements temporarily to see if logs show up for materialization

- sdk/python/feast/expediagroup/vectordb/milvus_online_store.py
- sdk/python/tests/expediagroup/test_milvus_online_store.py
MilvusOnlineStore update failed to create IVF_FLAT indexes
Renames IVFLAT to the expected string IVF_FLAT for those indexes.
Added test coverage for creating all supported index types.
> Bugfix: rename IVFLAT to the expected string IVF_FLAT

- go/README.md
- go/internal/feast/transformation/transformation.go
The go server will crash when the FFI call to the python transfromer for odfvs panics.
add a deferred func to catch any panics in the FFI call for transformations and turn them into an error instead
> Catch python FFI panic

- go/internal/feast/server/http_server.go
This pr allows customers to omit the "statuses" and "event_timestamps" from their responses to the /get-online-features endpoint when using the go feature server. 
Fixes #
> feat: Adding option to omit status response from go feature server response

- go/internal/feast/server/http_server.go
- go/internal/feast/transformation/transformation.go
- sdk/python/feast/ui_server.py
**What this PR does / why we need it**: 
Releases the memory used by [CGOArrowAllocator](https://github.com/apache/arrow/blob/go/v8.0.0/go/arrow/memory/cgo_allocator.go). Not releasing the memory causing the memory leaks. Pods restart after all the memory allocated by container is filled up. 
- Memory leak in GO code
- Fixes issue observed in building UI module
Fixes #
- Memory leak in GO code
- Fixes issue observed in building UI module
> fix: CGO Memory leak issue

- go/internal/feast/registry/http.go
- go/internal/feast/registry/registry.go
Uses caching for registry calls
Adding timestamp for messages when failed to refresh registry
> allowing cache for registry list calls

- sdk/python/feast/embedded_go/online_features_service.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/registry/http.py
- sdk/python/feast/infra/registry/sql.py
- sdk/python/tests/unit/test_sql_registry.py
1. HTTP Registry initialization failing with error "_refresh_lock" doesn't exist. When initializing registry in __init__ method, allow_cache to False for proto() function to avoid the error
2. Enabled background registry refresh. This process needs tuning. 
3. Updated get odfv and datasource functions to allow allow_cache functionality 
4. ODFV execution from Go Feature server uses cached odfv
5. Added support for delete_project in SQL Registry
6. cache_ttl_seconds is added to tests to the thread wait will not wait for default 600 seconds. This caused the increase in unit tests execution time. As mentioned in #2, this process needs tuning so we can send signal to stop thread when the execution is completed.
> fix: enabled cache background refresh for http registry

- go/internal/feast/registry/http.go
- go/internal/feast/transformation/transformation.go
- protos/feast/core/DataSource.proto
- protos/feast/core/Entity.proto
- protos/feast/core/FeatureService.proto
- protos/feast/core/FeatureView.proto
- protos/feast/core/OnDemandFeatureView.proto
- sdk/python/feast/infra/registry/http.py
- sdk/python/feast/infra/registry/sql.py
1. Added: defined list protos for feast objects
2. Made the registry threads as daemon so they will killed along with main thread
> fix: defined list protos for feast objects

- go/embedded/online_features.go
- go/internal/feast/featurestore.go
- go/internal/feast/registry/registry.go
- go/internal/feast/server/http_server.go
- protos/feast/core/Registry.proto
- sdk/python/feast/expediagroup/pydantic_models/project_metadata_model.py
- sdk/python/feast/infra/registry/http.py
- sdk/python/feast/infra/registry/sql.py
- sdk/python/feast/project_metadata.py
- sdk/python/tests/unit/test_pydantic_models.py
1. Allows cached calls to get_project_metadata
2. Added last_time_stamp to ProjectMetadata object. This avoids separate calls to get last_updated_timestamp 
3. Added some error logging to Go feature server
4. Leverage http registry cache for refresh in Http.py
> fix: Added caching to get project calls

- sdk/python/feast/infra/registry/sql.py
fix: formatted timestamp coming from projectmetadata proto correctly
> fix: formatted timestamp coming from projectmetadata proto correctly

- go.mod
- go.sum
- go/internal/feast/transformation/transformation.go
We are using unsafe pointers to execute arbitrary CPython FFI. Because this is so unsafe we occasionally encounter fatal errors that shut down the entire program. This change isolates the unsafe code and FFI call in a separate process that can handle the fatal errors as a panic in the parent.
Wrap unsafe code in isolated child process in case of a fatal error.
Return the output or error via channels
> create an isolated child process to run unsafe code and CFFI

- go/internal/feast/transformation/transformation.go
- go/internal/feast/transformation/transformation_test.go
The process Close() call was blocking the parent process and causing timeouts.
- the child closing itself
- parent only waits for the channel response to be ready
- add test for transformation
Fixes #
> Remove blocking during closing the chuld process

- go/internal/feast/transformation/transformation.go
- sdk/python/feast/embedded_go/online_features_service.py
We don't release the arrow memory if there are any errors which can cause a buildup of allocated memory. This ensures we always release the memory before returning out of the function.
> release arrow context before any return

- go/types/typeconversion.go
- go/types/typeconversion_test.go
- sdk/python/feast/infra/registry/sql.py
1. Handles nil values when converting from proto to arrow. (Example: Before integers are converted to 0 and strings are converted to ""). Now they are returned in the response as "null" so we can differentiate whether the value exists in Online store or not
2. Fixes the bug with Registry updates when multiple projects have the same feast object name
> fix: Handling nil values when converting from proto to arrow

- sdk/python/feast/expediagroup/vectordb/elasticsearch_online_store.py
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/tests/expediagroup/elasticsearch_online_store_creator.py
- sdk/python/tests/expediagroup/test_elasticsearch_online_store.py
- setup.py
Add Elasticsearch as an option for vector embeddings and features.
This implements the update method with full unit tests.
> Add elasticsearch online store - update method

- sdk/python/feast/expediagroup/vectordb/elasticsearch_online_store.py
- sdk/python/tests/expediagroup/test_elasticsearch_online_store.py
remove unneeded config value "token"
fix calls to eleasticsearch connection manager to use the online_store config
> fix elasticsearch connection manager calls

- docs/reference/online-stores/elasticsearch.md
- sdk/python/feast/expediagroup/vectordb/elasticsearch_online_store.py
Created capabilities documentation for ElasticsearchOnlineStore
> add elasticsearch documentation

- sdk/python/feast/expediagroup/pydantic_models/data_source_model.py
- sdk/python/feast/expediagroup/pydantic_models/feature_service.py
- sdk/python/feast/expediagroup/pydantic_models/feature_view_model.py
- sdk/python/feast/expediagroup/pydantic_models/stream_format_model.py
- sdk/python/tests/unit/test_pydantic_models.py
This PR adds KafkaSourceModel to Pydantic models, making KafkaSources viable data sources for transmission in service calls such as the ones in Registry Service.
https://jira.expedia.biz/browse/EAPC-9689
> Add KafkaSourceModel to Pydantic models

- sdk/python/feast/expediagroup/pydantic_models/data_source_model.py
- sdk/python/feast/infra/registry/http.py
- sdk/python/tests/unit/test_pydantic_models.py
adds a pydantic model for Push Sources so that they can be added to the feature registry
Fixes #
> feat: push source pydantic model

- sdk/python/feast/infra/registry/http.py
- sdk/python/feast/repo_config.py
What this PR does / why we need it:
This PR is adding client_id to http registry request headers and accepting the client_id in config.
It helps tracking the requests to registry.
> accepting client_id header

- go/internal/feast/registry/http.go
- sdk/python/feast/infra/registry/sql.py
Added logging to understand the time to refresh registry cache
chore: Added logging to understand the time to refresh registry cache
Fixes #
chore: Added logging to understand the time to refresh registry cache
> chore: Added logging to understand the time to refresh registry cache

- go/internal/feast/registry/registry.go
Fixes #
- When error occurs, return statement stop the goroutine. So registry won't refresh.
> fix: Refreshes the registry instead of stopping the background refresh

- sdk/python/feast/infra/registry/http.py
Fixes #
Support to apply Kafka Datasource in http registry
> fix: Support to apply Kafka Datasource in http registry

- sdk/python/feast/infra/contrib/spark_kafka_processor.py
- sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
Fixes #
1. ToPandas() not supporting boolean types so switching to mapInPandas() for stream
2. Feast made updates to Spark Materialization Engine to use mapInPandas already. So making that change to make it consistent with Feast
> fix: Using mapInPandas for both spark stream and batch ingestions

- sdk/python/feast/expediagroup/provider/expedia.py
Fixes #
fix: Support for feature view deletes using Expedia provider - Default behavior is to delete data from Redis online store when the feature view is deleted. We are not supporting this behavior because GH runner doesn't have access to Redis and it's not performant way to delete data.
> fix: Support for feature view deletes using Expedia provider

- java/serving-client/src/main/java/dev/feast/FeastClient.java
- java/serving-client/src/test/java/dev/feast/FeastClientTest.java
Added configurable deadlines for the Feast Java gRPC client. We need it because clients could otherwise [get stuck forever](https://grpc.io/docs/guides/deadlines/) waiting for the server to respond, and we should make it simpler for users of this library to implement retries and timeouts; especially when it's already supported by gRPC by default.
> Add deadline to Java gRPC client

- sdk/python/feast/expediagroup/provider/expedia.py
- sdk/python/feast/infra/registry/http.py
- Fixes the start up issues with Python Feature Server using HTTP Registry. HTTP Registry is throwing errors for the methods used in application start up. We don't need them in our use cases so it's not implemented. Returning empty response helps to fix the problem as a temporary work around. 
- Usage module is deleted by Feast. As we brought in new merges, we deleted that usage python module specific code from Expedia provider.
> fix: Start up issues in Python Feature server with HTTP Registry

- sdk/python/feast/expediagroup/pydantic_models/data_source_model.py
- sdk/python/feast/expediagroup/pydantic_models/feature_view_model.py
- sdk/python/feast/infra/registry/caching_registry.py
- sdk/python/feast/infra/registry/http.py
- sdk/python/feast/infra/registry/proto_registry_utils.py
- sdk/python/tests/unit/test_pydantic_models.py
1. timedelta is serialized and deserialized differently in V1. Changes made to make it compatible with V1 using field_serializer and field_validator. In V1 version, time delta is serialized to number of seconds and now its serialized to [±]P[DD]DT[HH]H[MM]M[SS]S ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format for timedelta)
2. setDaemon() is deprecated so using daemon property as recommended
3. parse_obj() and json() are deprecated in Pydantic V2. Using the recommended methods.
> fix: Fix compatibility issues between Pydantic V1 and V2 with timedelta

- go/README.md
- go/internal/feast/registry/repoconfig_test.go
- sdk/python/feast/on_demand_feature_view.py
- sdk/python/feast/transformation_server.py
- sdk/python/tests/unit/infra/scaffolding/test_repo_operations.py
- setup.py
1. Updated go ReadMe file
2. Added a test case in Go code to verify Environment variables are substituted when converting feature_store.yaml to RepoConfig
3. Using typing.get_type_hints instead of inspect.signature method to resolve forward references. inspect.signature returning string when return annotation is defined as forward reference. By importing `from __future__ import annotations` in feature definitions file, we can defer annotation which will return as string with inspect.signature.  
4.  Setting health service status for transformation service
> fix: Using typing.get_type_hints and set transformation service health status

- sdk/python/feast/infra/registry/http.py
1. tags argument need to be passed to Proto_registry_utils class to get the list of items from cache object
> fix: Add support for tags in HttpRegistry list methods when allow_cache is true

- sdk/python/feast/on_demand_feature_view.py
1. Used pandas mode for the ODFV objects that are already present in database
> chore: Default to pandas mode if not specified in ODFV proto in database

- sdk/python/feast/registry_server.py
Adds health check service to remote registry service
> feat: Add health check service to registry server

- Makefile
- pyproject.toml
- setup.py
Databricks images coming with protobuf 3.19.4. It meets the protobuf<5.0.0 requirements. so it's not overwriting the dependency. This will fix the issue.
> fix: Adding min required protobuf version

- setup.py
Databricks images coming with pyarrow v8.0.0. As the dependency says, pyarrow >=4, it's a valid pyarrow version. substrait module is only available from pyarrow v9.0.0
> fix: Pyarrow substrait module is available from 9.0.0 only

- go.mod
- go.sum
- go/main.go
Automatically set GOMAXPROCS to match Docker container CPU quota. This avoids users setting GOMAXPROCS environment variable.
> feat: Automatically set GOMAXPROCS to match container CPU quota

- sdk/python/feast/expediagroup/provider/expedia.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
- sdk/python/feast/repo_config.py
- setup.py
This PR is includes the addition of `lazy_table_creation` to `CassandraOnlineStoreConfig`.
`lazy_table_creation` is used in `feature_story.py`'s `apply` method to defer infra creation to the Materialization stage, found in this PR: https://github.com/ExpediaGroup/feast/pull/147.
https://jira.expedia.biz/browse/EAPC-14919
> feat: Lazy Infra Creation with online_store Option Set to True

- sdk/python/feast/infra/registry/sql.py
Populates project created_time correctly according to created time in feast_metadata table.
> fix: Populates project created_time correctly according to created time in feast_metadata table

- sdk/python/feast/infra/registry/http.py
When trying to validate/register features with the most up to date version of eg-feast (after ScyllaDB additions and Project Object additions), users were getting failures because of 404s when trying to retrieve their project.
[Slack thread](https://expedia.slack.com/archives/C0425D3PS72/p1733206078407869)
This applies the project_metadata once again to solve the issue.
https://jira.expedia.biz/browse/EAPC-15745
> fix: Correct apply_project in HttpRegistry

- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/cassandraonlinestore_test.go
- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
feat: Implement key batching for cassandra online store in go feature server.
> feat: Implement key batching for cassandra online store in go feature server.

- sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
This PR allows instances of the OnlineStore to be shared from within the spark materialization engine. This means a new connection to the store doesn't need to be created for each write.
> fix: Reuse online store for materialization writes

- go/internal/feast/onlinestore/cassandraonlinestore.go
Moving the batch length caching logic outside of go routine.
Fixes the intermittent issue thats happening in the feature server go routine.
Error: failed to scan features: gocql: expected 47 values send got 50","time":"2025-01-30T16:32:39Z","message":"Error getting feature vector"
> fix: Using correct CQL Statement for scylla read calls

- sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
Improving the logging for Spark materialization engine. Earlier we are printing time for each iterator. Now it prints the metrics for all iterators. Reduces the logging which we used to do in the past and also give additional information with this change.
> fix: Improve logging for spark materialization engine

- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/cassandraonlinestore_test.go
- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
- sdk/python/tests/unit/infra/online_store/test_cassandra_online_store.py
Scylladb has a limit of 48 characters for table names. With this approach, trying to use hash of the table name and project name to control it. Validation module validates the table name for the given project and feature view names if it has any conflicts.
> fix: Fix Scylladb table name limitation

- go/internal/feast/onlinestore/cassandraonlinestore.go
Fixes go static analyzer warnings. Warning is `assignment copies lock value to results[serializedEntityKeyToIndex[keyString]][featureNamesToIdx[featName]]: github.com/feast-dev/feast/go/internal/feast/onlinestore.FeatureData contains github.com/feast-dev/feast/go/protos/feast/serving.FeatureReferenceV2 contains google.golang.org/protobuf/runtime/protoimpl.MessageState contains sync.Mutex`
> fix: Fixing go static analyzer warnings

- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/cassandraonlinestore_test.go
- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
- sdk/python/tests/unit/infra/online_store/test_cassandra_online_store.py
1. Made it backward compatible with current implementation of feast by introducing `table_name_format_version`. Defaulted to 1. 
2. Further compressing the md5 output with base62 encoding. All the table names are used in double quotes so they are case sensitive. 
3. Raise exception if the given table_name_format_version is invalid
> fix: Table name format is backward compatible

- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/registry/repoconfig_test.go
fix: Correct type conversion for table name format version. By default it's casted to float64. We need to cast it from float64 to int. We need to add tests to NewCassandraOnlineStore function to fully fix the problem.
> fix: Correct type conversion for table name format version

- sdk/python/feast/infra/registry/base_registry.py
SortedFeatureView was not getting properly registered.
- add SortedFeatureView to base registry deserialize_registry_values method
> fix: Add SortedFeatureView to base registry deserialize values method

- go/internal/feast/featurestore.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- go/internal/feast/registry/http.go
- go/internal/feast/registry/http_test.go
- go/internal/feast/registry/registry.go
- go/internal/feast/server/logging/featureserviceschema.go
- go/internal/feast/server/logging/featureserviceschema_test.go
- go/internal/feast/server/logging/service.go
- go/internal/test/go_integration_test_utils.go
- protos/feast/core/SortedFeatureView.proto
Add SortedFeatureView to registry calls and feature service in Go feature server
- add missing list proto for SortedFeatureView
- add SortedFeatureView to registry calls and caching
- add SortedFeatureView to feature service
- add SortedFeatureView to feature/refs lookup
> feat: Add sorted feature view to registry calls and feature server for Go

- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
1. Added feature view name when required entity key is missing in the request
2. Added warnings to Cassandra online store when rate limit is reached or waiting for all futures to complete. Default query timeout is None which means operation doesn't timeout. This can lead to indefinite wait sometimes. Be cautious without setting request_timeout.
> fix: Enhance error messages for missing keys and  logging in Cassandra

- sdk/python/feast/sorted_feature_view.py
I am trying to register a sorted feature view, but its failing:
https://github.expedia.biz/eg-ai-platform/mlpfs-scylladb-perf-test/actions/runs/34957239/job/54371136
And I am thinking its because hash() is not implemented for the sorted feature view. Hence I added it in this PR.
> fix: Make Sorted feature view hashable

- java/pom.xml
- java/serving-client/src/main/java/dev/feast/FeastClient.java
1/ Add [serviceConfig](https://grpc.io/docs/guides/service-config/)  to client. This allows a consumer to specify HTTP 2.0 specifications, such as configuring retries/timeout/etc.
N/A
N/A
> feat: Add serviceConfig to java-serving-client

- go/internal/feast/featurestore.go
- go/internal/feast/featurestore_test.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/onlinestore.go
- go/internal/feast/onlinestore/redisonlinestore.go
- go/internal/feast/onlinestore/sqliteonlinestore.go
- go/internal/feast/server/grpc_server.go
- go/types/typeconversion.go
- go/types/typeconversion_test.go
- protos/feast/serving/GrpcServer.proto
- protos/feast/serving/ServingService.proto
This PR adds support for range queries on sorted featureviews within the go grpc server. It adds the GetOnlineFeaturesRanges to the grpc server and the go feature store. Important to note that we're currently not supporting OnDemadFeatureViews or Feature Service usage with GetOnlineFeaturesRange.
> feat: Add Support for Range Query Retrievals in Go Grpc Server

- go/internal/feast/featurestore.go
- go/internal/feast/featurestore_test.go
- go/internal/feast/model/sortedfeatureview.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/cassandraonlinestore_test.go
- go/internal/feast/onlinestore/onlinestore.go
- go/internal/feast/onlinestore/redisonlinestore.go
- go/internal/feast/onlinestore/sqliteonlinestore.go
- go/main.go
- go/types/typeconversion.go
- go/types/typeconversion_test.go
Draft based on https://github.com/ExpediaGroup/feast/pull/192 with some minor modifications for per-reversing the order of the sort key filters.
Generates a CQL statement based on the requested features and sort key filters
> feat: Go range query implementation for scylladb

- go/embedded/online_features.go
- go/internal/feast/server/grpc_server.go
- go/internal/feast/server/http_server.go
- go/internal/feast/server/hybrid_server.go
- go/internal/feast/server/server_commons.go
- go/main.go
Changelist: 
1/ Created type `StartHybridServer` which starts both http/gRPC servers 
2/ Added combinedHealthCheck method. 
Context on combinedHealthCheck: 
Kubernetes does readiness/liveness probes via the health endpoint(note that both checks simply poll this endpoint). The general pattern is to configure a single probe per container. As we are creating two independent servers we need to have a combined health-check to validate that both servers are healthy. Kubernetes should probe via the /health endpoint and simply validates that the status is in 200-399.
https://grpc.io/docs/guides/health-checking/
https://github.com/kubernetes/kubernetes/blob/ef838fcc3fa3b43c2e67b4e43d71b6720fc61898/pkg/probe/grpc/grpc.go#L53
Looking for feedback here, there may be a better way to do this. One …
> feat: Add hybrid server type, spins up both http/gRPC servers

- go/internal/feast/featurestore_test.go
- go/internal/feast/model/sortedfeatureview.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/cassandraonlinestore_test.go
- go/internal/feast/server/grpc_server.go
- java/serving-client/src/main/java/dev/feast/RangeQueryModel.java
- java/serving-client/src/main/java/dev/feast/RequestUtil.java
- java/serving-client/src/main/java/dev/feast/SortKeyFilterModel.java
- java/serving-client/src/test/java/dev/feast/FeastClientTest.java
- java/serving-client/src/test/java/dev/feast/RequestUtilTest.java
- protos/feast/serving/ServingService.proto
Add equals option to SortKeyFilter and validate that only the last sort key filter uses a range query
Support for multiple sort keys
The main change is the SortKeyFilter proto, changing to a oneof:
`    oneof query {
RangeQuery range = 2;
feast.types.Value equals = 3;
}`
Please review validation test cases for any missed variations.
> feat: Add equals option to SortKeyFilter and validate

- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/registry/http.py
Exclude SortedFeatureViews from list of FeatureViews to be deleted, otherwise Delete operation is attempted twice on SortedFeatureViews
**Test**:
Renaming/deleting feature view was successful after the above change-
https://github.expedia.biz/eg-ai-platform/mlpfs-scylladb-perf-test/actions/runs/35665934
> fix: Fix/delete sfv

- sdk/python/feast/infra/registry/caching_registry.py
- sdk/python/feast/infra/registry/sql.py
Some projects have a large number of feature views that can overload the registry cache. This adds the option to exempt projects from caching.
> feat: Add option to exempt projects from caching in sql registry

- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
- sdk/python/tests/expediagroup/test_cassandra_online_store.py
Currently, `key_ttl_seconds` in `online_store` config is being used to set TTL in Online store. Also theTTL is activated based on the time when data is written in to Scylla DB as mentioned [here](https://opensource.docs.scylladb.com/stable/cql/time-to-live.html#expiring-data-with-time-to-live-ttl)
In this PR, the idea is to set TTL using the `ttl` field in the Feature View definition and also TTL is calculated based on the event timestamp but not the time at which data is written into Scylla DB.
For example, lets say right now we are materializing data that is an hour old (meaning event timestamps are an hour old) and the TTL that user configured is 3hrs. Then the final/effective TTL that will be set in Scylla DB will be 2hrs. This is because an hour is already elapsed between the event …
> feat: Use feature view ttl in Scylladb

- go/internal/feast/onlinestore/egvalkeyonlinestore.go
- go/internal/feast/onlinestore/egvalkeyonlinestore_test.go
- sdk/python/feast/infra/online_stores/eg_valkey.py
Address of the replica node used for read operations in GO Feature Server for Valkey Standalone clusters. 
Supports reading from read replicas in Valkey Standalone clusters.
> feat: Support for replica addresses for valkey

- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/cassandraonlinestore_test.go
Adding batching for range querying to improve performance.
> feat: Adding batched online read range for scylladb

- sdk/python/feast/infra/registry/sql.py
- sdk/python/feast/infra/registry/sql_fallback.py
- sdk/python/tests/integration/registration/test_universal_registry.py
Creates a new type of Sql registry that includes live db calls as a fallback.
Additionally, whenever any data from the database is retrieved (whether allow_cache=True or False), the cache is updated with the retrieved data. List functions completely overwrite the cache for that object type unless the request includes tags, in which case the cache is not updated.
Allows for fallback to the db when the registry cache is missing the requested data as well as force-refreshing the cache with the db data.
Updated SqlRegistry `_get_sorted_feature_view` to match of `_get_<type>_feature_view` definitions.
> feat: Create a new sql registry class that fallback to live calls when cache fails

- go/internal/feast/server/grpc_server.go
- go/internal/feast/server/hybrid_server.go
- go/main.go
1/ We need to add changes to the health-check s.t. it actually calls the health server from a client. The health.server check endpoint just checks the internal servingStatus enum, this would be initialized as 'SERVING', therefore if the server itself doesn't spawn then the enum value 'SERVING' would remain.
2/ Move httpServer listen to goroutine as it's a blocking call.
> fix: Hybrid server kubernetes health endpoint invalid if server isn't started

- go/internal/feast/featurestore_test.go
- go/internal/feast/model/sortedfeatureview.go
- go/internal/feast/model/test/sortedfeatureview_test.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/cassandraonlinestore_test.go
We identify if the sort key order is reversed is true, if it is true use unbatchedOnlineReadRange instead of BatchedOnlineReadRange as ScyllaDB doesn’t allow for PARTITION BY & ORDER BY in the same query.
> feat: Adding in sortOrder check for OnlineReadRange Functionality

- go/internal/feast/featurestore.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/server/http_server.go
This PR adds the implementation of range query to the http go server. 
Example request:
```
curl -X POST \
"https://{test-url}/get-online-features-range?status=true" \
-d '{      
"features": [            
"batch_mat_sorted_fv:feature_1",
"batch_mat_sorted_fv:feature_2",
"batch_mat_sorted_fv:feature_3"
],      
"entities": {    
"entity_key": [  
"entity_key_4"
]
},          
"sort_key_filters": [
{                    
"sort_key_name": "event_timestamp",
"range_start": 1740000000,
"start_inclusive": false,
"end_inclusive": false
}
],
"reverse_sort_order": false,
"limit": 10,
"full_feature_names": true
}'
```
Response:
```
'{
"metadata": {
"feature_names": [
"entity_key",
"batch_mat_sorted_fv__feature_1",
"batch_mat_sorted_fv__feature_2",
"batch_mat_sorted_fv__feature_3"
]
},
"results": [ …
```
> feat: Go http server range query support

- sdk/python/feast/infra/registry/sql_fallback.py
- sdk/python/tests/integration/registration/test_universal_registry.py
The current caching system periodically queries the db for the complete list of objects per type and stores them in a list format. This cache loading is also done via a thread pool executor that makes a thread per project. This has caused many issues with threads being maxed out which cascades into errors in the cache.
This PR moves to a new lazy-cache system where objects not found in the cache are queried from the db, then stored in a map structure with a ttl. The refresh process now executes with a thread per cache map wherein each object's ttl is checked for expiration and if expired the object is queried from the db and restored. If the object is no longer found, it is removed from the cache. This should drastically reduce the number of threads created during refresh as well as …
> feat: Completely rewrite the sql fallback caching system to only use lazy caching with a map structure

- java/pom.xml
- java/serving/src/test/java/feast/serving/it/ServingRedisS3RegistryIT.java
Upgrading GRPC version 1.30.2 to 1.53.0. 1.30.2 is very old version (Jun, 2020) upgrading to 1.53.0 (which is also not latest). 1.53.0 is the current lowest version used internally. This eventually upgrades to Latest version.
> fix: Upgraded java grpc version from 1.30.2 to 1.53.0

- go/internal/feast/registry/http_test.go
- go/internal/feast/registry/registry.go
Cache maps were not properly initialized in go feature server.
Initializes cache maps on load. If project key is missing in a cache map, create the underlying map.
> fix: Set project map if not exists in cache map

- go/internal/feast/registry/registry.go
- go/internal/feast/registry/registry_test.go
The go server registry had no units allowing bugs to slip through. This should ensure the cache is working properly.
Fixes bug where the ttl for objects were not set properly.
> fix: Create units tests for registry caching and fallback

- go/internal/feast/server/grpc_server.go
- java/serving-client/src/main/java/dev/feast/FeastClient.java
- java/serving-client/src/main/java/dev/feast/RangeRow.java
- java/serving-client/src/main/java/dev/feast/Row.java
- java/serving-client/src/test/java/dev/feast/FeastClientTest.java
- protos/feast/serving/ServingService.proto
1/ Add status parameter as FieldStatus/Timestamps increase the size of the response body. Currently we support the inclusion of status via a query parameter 'status' for the http_server.
2/ Remove status/timestamps from the serving-client body. We do not parse the FieldStatus/timestamps in the middleware currently.
> fix: Add optional status parameter to grpc_server, serving-client

- go/internal/feast/featurestore_test.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
This PR makes the getUniqueEntityRows method deterministic. This makes the GroupSortedFeatureRefs and GroupFeatureRefs methods return the same object every time and makes testing it easier.
> fix: Make getUniqueEntityRows response deterministic

- go/internal/feast/onlinestore/cassandraonlinestore.go
Changing the default table name format version to Float. Registry converts integers to Float. Default value is INT so its throwing error when not specified in feature_store.yaml
Error is: `panic: interface conversion: interface {} is int, not float64`
fix: Changing the default table name format version to Float
> fix: Changing the default table name format version to Float

- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/onlinestore/egvalkeyonlinestore.go
- go/internal/feast/onlinestore/redisonlinestore.go
- go/internal/feast/onlinestore/sqliteonlinestore.go
- go/internal/feast/onlinestore/unmarshal_utils.go
- go/internal/feast/server/grpc_server_integration_test.go
Currently, UnixTimestamp values that should be null or serialized as a minimum int64 value instead of a true null.
Create a common unmarshal function for serialized protos that sets timestamp values should be null to null.
> fix: Create common func to unmarshal protos and handle null timestamps

- go/internal/feast/server/http_server.go
While sending a request to the Feature Server we are only able to read the “Include Metadata” parameter in camel case, we must also include snake case option in the request.
> fix: Adding Snake Case to Include Metadata Check

- protos/feast/core/SortedFeatureView.proto
- sdk/python/feast/expediagroup/pydantic_models/feature_view_model.py
- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
- sdk/python/feast/sorted_feature_view.py
use_write_time_for_ttl config should be a feature view level config instead of on the whole online store
> fix: Move use_write_time_for_ttl config to sfv instead of an online store config

- sdk/python/feast/sorted_feature_view.py
- sdk/python/tests/unit/test_sorted_feature_view.py
Adding clearer error messages with sfv names mentioned in them.
> fix: Clean Up Error Messages

- go/internal/feast/integration_tests/scylladb/scylladb_integration_test.go
- go/internal/feast/integration_tests/valkey/valkey_integration_test.go
- go/internal/feast/server/grpc_server_test.go
- go/internal/feast/server/http_server.go
- go/internal/feast/server/server_test_utils.go
- go/types/typeconversion.go
- go/types/typeconversion_test.go
Http range timestamp values should return in rfc3339 format to match how get features timestamps are returned.
Timestampp spec states that datetimes should always be displayed as UTC in json.
Arrow marshaling uses a slight variation of RFC3339, using their format string to remain consistent.
> fix: Http range timestamp values should return in rfc3339 format

- go/internal/feast/integration_tests/scylladb/scylladb_integration_test.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- go/types/typeconversion.go
SortKeyFilter validation was throwing an error for if any filter was not any equals except the very last defined sort key. It should allow the last requested filter to be range even if it is not the last defined sort key.
HTTP requests sometimes unmarshal integer values as int32 instead of int64.
SortKeyFilter logic updated
Added value conversion from int32 to int64/unix timestamp for entities and sort key filters from http.
> fix: Validation order for multiple missing end keys should pass

- go/internal/feast/featurestore_test.go
- go/internal/feast/integration_tests/scylladb/scylladb_integration_test.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/onlineserving/serving_test.go
- go/internal/feast/onlinestore/cassandraonlinestore.go
- go/internal/feast/server/http_server.go
- go/internal/feast/server/http_server_test.go
- go/types/typeconversion.go
- go/types/typeconversion_test.go
1. Fail if number of values doesn't match with number of Status fields
2. When requested entity key has all NULL values for limit specified, it was represented as array with null value. Now its represented as array of null values with requested limit or number of records exists in Database
3. RepeatedProtoValuesToArrowArray appends NULL values if repeatedValue is nil. 
4. Removed unused code in ArrowValuesToRepeatedProtoValues. Removed invalid test TestProtoValuesToRepeatedConversion and associated code
5. Logic changed for HTTP response when metadata is requested. Currently it shows NIL values and empty timestamps. Updated it to represent correctly. 
6. Updated valueTypeToGoTypeTimestampAsString to represent NULL values in HTTP response as NULL instead of empty array `[]`
> fix: Handle null values in Arrow list conversion to Proto values

- go/types/typeconversion.go
- go/types/typeconversion_test.go
> fix: When given a string for a bytes entity/sort key filter, attempt to convert as base64 string

- sdk/python/feast/infra/registry/http.py
Adding a check to see if HTTPStatusError is being raised within _handle_exception and if it is, to return the same so that the HTTPStatusError is executed and raises the right error when get_feature_view is called in the Http registry.
> fix: Update Feature View Not Catching SortedFeatureView/FeatureView Errors

- sdk/python/feast/infra/contrib/spark_kafka_processor.py
- sdk/python/feast/infra/passthrough_provider.py
Streaming ingestion latencies were ranging from 10sec to 30sec after 1K TPS, which is not desirable. The purpose of this PR is to improve the latencies by parallelizing the time-consuming portions of the code using multiprocessing. Most of the latencies are coming from [arrow_to_proto conversion](https://github.com/ExpediaGroup/feast/blob/bf641bd1230d11fc77b64383f6446dc9b4d101b1/sdk/python/feast/infra/passthrough_provider.py#L295) and [online_write_batch](https://github.com/ExpediaGroup/feast/blob/bf641bd1230d11fc77b64383f6446dc9b4d101b1/sdk/python/feast/infra/passthrough_provider.py#L297). To address that, in this PR, the input dataframe/ arrow table is split into smaller inputs, and then they are processed in parallel on multiple cores/processes using multiprocessing.
The number of …
> feat: Streaming ingestion latency improvements
